name: Copilot Code Review
on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  copilot-review:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Copilot review
        uses: github/copilot-code-review@v1
